name: rps
title: Rock Paper Scissors
module: apps.rps.backend.server
capabilities:
  - database
  - realtime
imports:
  - monotools.orchestration.management
  - monotools.persistence.auth
  - monotools.persistence.database
  - monotools.persistence.orm
  - monotools.runtime.appkit
  - monotools.runtime.application
  - monotools.runtime.http
  - monotools.runtime.realtime
frontend:
  artifacts:
    index:
      format: lit
      source: frontend/index.js
      output: index.html
  routes:
    /: index
