name: quiz
title: Working Style Inventory
module: apps.quiz.backend.server
imports:
  - monotools.management
  - monotools.runtime
frontend:
  artifacts:
    index:
      format: lit
      source: frontend/index.js
      output: index.html
  routes:
    /: index
