/** Calculator's server-owned Lit page entry. */

import { html, render } from "lit";
import "@xenorepo/lit-ui";

type LedgerEntry = { sequence: string; time: string; expression: string; result: string };
type CalculatorState = {
  current: string; stored: number | null; operation: string | null; replace: boolean;
  memory: number; sequence: number; ledger: LedgerEntry[]; expression: string;
};

const storageKey = "calc98-state-v1";

/** Mount the calculator without introducing a client-side router. */
export function mount(root: HTMLElement): void {
  render(html`
    <style>
      :host, * { box-sizing: border-box; } .frame { height: 100vh; display:grid; grid-template-rows:28px minmax(0,1fr) 24px; }
      .mosaic { min-height:0; display:grid; grid-template-columns:156px minmax(320px,1fr) 210px; grid-template-rows:minmax(290px,62%) minmax(150px,38%); gap:1px; }
      x-console-pane { min-width:0; min-height:0; } .memory {grid-row:1/3}.workspace {grid-column:2}.inspector {grid-column:3}.ledger {grid-column:2/4}
      .memory-list { margin:0; padding:5px; list-style:none; } .memory-list button {width:100%; margin-bottom:4px; text-align:left} .memory-list b {float:right}
      .display-zone {height:100%; display:grid; grid-template-rows:auto auto minmax(56px,1fr) auto}.tabs {display:flex}.tab {padding:3px 12px}.expression {padding:8px 12px 0;text-align:right}.readout {display:flex;align-items:center;justify-content:flex-end;padding:4px 12px;font-size:clamp(28px,5vw,58px);font-weight:bold}.error {color:var(--red)}
      .keypad {display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:4px;padding:7px}.calc-key {min-height:35px}.equals {grid-row:3/5;grid-column:5}.wide {grid-column:span 2}.op {color:var(--yellow)}
      dl {display:grid;grid-template-columns:1fr auto;margin:0}dt,dd {margin:0;padding:5px 7px;border-bottom:1px solid var(--line)}dd {text-align:right}.meter {height:8px;margin:0 7px;background:var(--well)}.meter i {display:block;width:4%;height:100%;background:var(--green)}
      table {width:100%;border-collapse:collapse;table-layout:fixed}th,td {padding:4px 7px;text-align:left;border-bottom:1px solid var(--line);overflow:hidden;text-overflow:ellipsis;white-space:nowrap}th {color:var(--yellow)}td:last-child {text-align:right}.empty td{text-align:center;padding:18px}.status {display:flex;justify-content:space-between}.live {margin-left:auto}
      @media(max-width:850px){.mosaic{grid-template-columns:146px minmax(280px,1fr)}.inspector{display:none}.ledger,.workspace{grid-column:2}} @media(max-width:560px){.mosaic{grid-template-columns:1fr;grid-template-rows:minmax(330px,64%) minmax(140px,36%)}.memory{display:none}.workspace,.ledger{grid-column:1}.optional,.hint{display:none}}
    </style>
    <x-console-shell class="frame" aria-label="Calculation control instrument">
      <x-utility-rail slot="header"><strong>▣ CALC/98</strong><span>ARITHMETIC CONTROL STATION / LOCAL</span><span class="live"><x-status-indicator></x-status-indicator><span id="summary">READY · 0 OPS</span></span><x-command-button id="copy" class="optional">COPY</x-command-button><x-command-button id="clearAll">RESET</x-command-button></x-utility-rail>
      <section class="mosaic"><x-console-pane class="memory" index="01" title="MEMORY BANK" tone="blue"><ul class="memory-list"><li><button data-memory="mc">MC <b id="memoryValue">0</b></button></li><li><button data-memory="mr">MR <b>RECALL</b></button></li><li><button data-memory="m+">M+ <b>ACCUM</b></button></li><li><button data-memory="m-">M− <b>REDUCE</b></button></li></ul></x-console-pane>
      <x-console-pane class="workspace" index="02" title="PRIMARY WORKSPACE" tone="green"><div class="display-zone"><div class="tabs"><button class="tab">STANDARD</button><button class="tab" disabled>SCIENTIFIC</button></div><div class="expression" id="expression">Awaiting input</div><output class="readout" id="display" aria-live="polite">0</output><div class="keypad">${["AC|clear","+/−|sign","%|percent","÷|op:÷","⌫|backspace","7|digit:7","8|digit:8","9|digit:9","×|op:×","√|sqrt","4|digit:4","5|digit:5","6|digit:6","−|op:−","=|equals","1|digit:1","2|digit:2","3|digit:3","+|op:+","0|digit:0",".|decimal","1/x|invert"].map(item => { const [label, action] = item.split("|"); const [kind, value] = action.split(":"); const attributes = kind === "op" ? { op: value } : kind === "digit" ? { digit: value } : { action: kind }; return html`<button class="calc-key ${kind === "op" ? "op" : ""} ${kind === "equals" ? "equals" : ""} ${label === "0" ? "wide" : ""}" data-op=${attributes.op ?? ""} data-digit=${attributes.digit ?? ""} data-action=${attributes.action ?? ""}>${label}</button>`; })}</div></div></x-console-pane>
      <x-console-pane class="inspector" title="03 REGISTER STATE"><dl><dt>MODE</dt><dd>DECIMAL</dd><dt>ACCUMULATOR</dt><dd id="accumulator">EMPTY</dd><dt>OPERATOR</dt><dd id="operator">NONE</dd><dt>MEMORY</dt><dd id="memoryState">CLEAR</dd></dl><div>CAPACITY <span id="capacity">1 / 12</span></div><div class="meter"><i id="capacityBar"></i></div></x-console-pane>
      <x-console-pane class="ledger" title="04 OPERATION LEDGER"><table><thead><tr><th>SEQ</th><th>TIME</th><th>EXPRESSION</th><th>RESULT</th></tr></thead><tbody id="history"></tbody></table></x-console-pane></section>
      <x-status-rail slot="footer" class="status"><span>● NOMINAL · BASE 10</span><span class="hint">0–9 INPUT · ENTER EXECUTE · ESC CLEAR</span><span id="clock">--:--:--</span></x-status-rail>
    </x-console-shell>`, root);
  const $ = (id: string) => root.querySelector<HTMLElement>(`#${id}`)!;
  let current = "0", stored: number | null = null, operation: string | null = null, replace = true, memory = 0, sequence = 0, ledger: LedgerEntry[] = [];
  const format = (value: number) => Number.isFinite(value) ? Number.parseFloat(value.toPrecision(12)).toString() : "ERROR";
  const drawLedger = () => { const history = $("history"); history.replaceChildren(); if (!ledger.length) history.innerHTML = '<tr class="empty"><td colspan="4">NO COMPLETED OPERATIONS</td></tr>'; else ledger.forEach(entry => { const row = history.insertRow(); [entry.sequence, entry.time, entry.expression, entry.result].forEach(value => row.insertCell().textContent = value); }); };
  const save = () => { try { localStorage.setItem(storageKey, JSON.stringify({ current, stored, operation, replace, memory, sequence, ledger, expression: $("expression").textContent })); } catch {} };
  const renderState = () => { $("display").textContent = current; $("display").classList.toggle("error", current === "ERROR"); $("accumulator").textContent = stored === null ? "EMPTY" : format(stored); $("operator").textContent = operation ?? "NONE"; $("memoryValue").textContent = format(memory); $("memoryState").textContent = memory === 0 ? "CLEAR" : "SET"; const digits = current.replace(/[-.]/g, "").length; $("capacity").textContent = `${Math.min(digits, 12)} / 12`; $("capacityBar").style.width = `${Math.min(digits / 12 * 100, 100)}%`; $("summary").textContent = `READY · ${sequence} OP${sequence === 1 ? "" : "S"}`; save(); };
  const clear = () => { current="0"; stored=null; operation=null; replace=true; $("expression").textContent="Awaiting input"; renderState(); };
  const calculate = () => { if (stored === null || !operation) return; const left=stored, right=Number(current), op=operation; current=format(({ "+":left+right, "−":left-right, "×":left*right, "÷":right === 0 ? NaN : left/right } as Record<string,number>)[op]); sequence++; ledger.unshift({sequence:String(sequence).padStart(3,"0"),time:new Date().toLocaleTimeString([], {hour12:false}),expression:`${format(left)} ${op} ${format(right)}`,result:current}); drawLedger(); stored=null; operation=null; replace=true; $("expression").textContent=current === "ERROR" ? "Division by zero / invalid operation" : `Result committed: ${current}`; renderState(); };
  const press = (button: HTMLButtonElement) => { const d=button.dataset.digit, op=button.dataset.op, action=button.dataset.action; if (d) { current=(current === "ERROR" || replace) ? d : current.replace(/[-.]/g,"").length < 12 ? (current === "0" ? d : current+d) : current; replace=false; } else if (op) { if (stored !== null && !replace) calculate(); stored=Number(current); operation=op; replace=true; $("expression").textContent=`${format(stored)} ${op}`; } else if (action === "equals") calculate(); else if (action === "clear") clear(); else if (action === "decimal") { if (current === "ERROR" || replace) {current="0.";replace=false;} else if (!current.includes(".")) current += "."; } else if (action === "backspace") current=!replace && current.length>1 ? current.slice(0,-1) : "0"; else if (action) { const value=Number(current); current=format(action === "sign" ? -value : action === "percent" ? value/100 : action === "sqrt" ? Math.sqrt(value) : action === "invert" ? 1/value : value); replace=true; $("expression").textContent=`${action.toUpperCase()}(${current})`; } renderState(); };
  root.querySelector(".keypad")!.addEventListener("click", event => { const button=(event.target as Element).closest<HTMLButtonElement>("button"); if (button) press(button); }); root.querySelector(".memory-list")!.addEventListener("click", event => { const action=(event.target as Element).closest<HTMLButtonElement>("button")?.dataset.memory; if (!action) return; if(action==="mc")memory=0; if(action==="mr"){current=format(memory);replace=true;} if(action==="m+")memory+=Number(current); if(action==="m-")memory-=Number(current); renderState(); });
  $("clearAll").onclick=()=>{clear();memory=0;sequence=0;ledger=[];drawLedger();renderState();}; $("copy").onclick=()=>navigator.clipboard?.writeText(current); addEventListener("keydown", event => { const map: Record<string,string>={"-":"−","*":"×","/":"÷"}; if(event.key>="0"&&event.key<="9") press(root.querySelector(`[data-digit="${event.key}"]`)!); else if(event.key===".")press(root.querySelector("[data-decimal]")!); else if(map[event.key]||event.key==="+")press(root.querySelector(`[data-op="${map[event.key]||event.key}"]`)!); else if(event.key==="Enter"||event.key==="=") calculate(); else if(event.key==="Escape")clear(); else return; event.preventDefault(); });
  setInterval(() => { $("clock").textContent = new Date().toLocaleTimeString([], {hour12:false}); }, 1000); try { const state=JSON.parse(localStorage.getItem(storageKey) ?? "null") as CalculatorState | null; if(state && typeof state.current === "string" && Array.isArray(state.ledger)){({current,stored,operation,replace,memory,sequence,ledger}=state);$("expression").textContent=state.expression || "Awaiting input";drawLedger();} } catch {} drawLedger(); renderState();
}
