name: microblog
title: WIRE/98
module: apps.microblog.backend.server
capabilities:
  - database
imports:
  - "@xenorepo/ui"
  - monotools.orchestration.management
  - monotools.persistence.auth
  - monotools.persistence.database
  - monotools.runtime.appkit
  - monotools.runtime.application
  - monotools.runtime.http
frontend:
  artifacts:
    index:
      format: preact
      source: frontend/index.tsx
      output: index.html
  routes:
    /: index
