name: kanban
title: Kanban
module: apps.kanban.backend.server
capabilities:
  - database
  - monoform
imports:
  - monotools.orchestration.management
  - monotools.runtime.appkit
  - monotools.runtime.application
  - monotools.runtime.http
  - monotools.runtime.monoform
  - "monoui"
frontend:
  artifacts:
    index:
      format: preact
      source: frontend/index.tsx
      output: index.html
  routes:
    /: index
