name: calculator
title: Calculator
module: apps.calculator.backend.server
frontend:
  artifacts:
    index:
      format: lit
      source: frontend/index.ts
      output: index.html
  routes:
    /: index
