name: calculator
title: Calculator
module: apps.calculator.backend.server
imports:
  - "@xenorepo/ui"
  - monotools.management
  - monotools.runtime
frontend:
  artifacts:
    index:
      format: preact
      source: frontend/index.tsx
      output: index.html
  routes:
    /: index
